### PR TITLE
[TASK] Update default HTML layout to match Twitter Bootstrap 3.x

### PR DESCRIPTION
**Pull request by pvanhemmen**
The HTML has been updated for basic bootstrap 3.x support. I didn't apply any fancy styling yet, just updated classes where possible and straightened out some glitches, so that there's a clean base that can be build upon.

I can do some additional styling, but I'd rather keep the code base clean to allow for easy customizing, what do you think?

Feedback is very welcome.

### CODE REVIEW

**Comment by fnagel** [comment]
Fixes #24

**Comment by fnagel** [comment]
Looks good from viewing. I will test this asap and give some in detail feedback.

Thanks again for your contribution, very appriciated!

**Comment by pvanhemmen** [comment]
You're welcome. I will make use of this extension in a private project, so the least I can do is contribute. I just random picked some tasks, if you have a specific request you want to focus on, just let me know - I'd be glad to help!

**Comment by fnagel** [comment]
No, just work on what ever suits your needs! I'm open to suggestion, too.

Anyway, there are some issues which I could need a little help. The documentation could need some love, we really needs some tests (#11) and Trackback / Pingback support is still missing (#13).

**Comment by fnagel** [comment]
I've added a new Bootstrap3 branch based on this PR: https://github.com/fnagel/t3extblog/commits/bootstrap3

Please give feedback here: #77

**Comment by fnagel** [comment]
Merged here: eac98aa7d822b69e30a3ffeff225c6fa64021aef

**Pull request closed without merging**
