### PR TITLE
Add types to Content model

### PR DESCRIPTION
**Pull request by garfieldius**
This resolves the TypeError described in #266

### CODE REVIEW

**Review by josefglatz — APPROVED** [review]

**Review by fnagel — APPROVED** [review]

**Comment by fnagel** [comment]
@garfieldius Looks good to me! Thanks a lot for your contribution!

**Comment by fnagel** [comment]
Try closing and re-oping the ticket in order to force a new GH action run. Not sure why one of those still fails, commit message looks good to me...

**Comment by fnagel** [comment]
Seems this is an issue with the GH action I'm using here: https://github.com/GsActions/commit-message-checker/issues/95

**Comment by fnagel** [comment]
Another try with updated workflow.

**Comment by fnagel** [comment]
Merged. Commit messages was finde, its really just the workflow: https://github.com/fnagel/t3extblog/actions/runs/6869676303

**Pull request merged**
