### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by criwe**
Documentation for t3extblog!

* [x] Fix all comments within the commits
* [x] Add a section which explains when Emails are sent (Prepare a section and I will fill it with content)
* [x] Configuration page does not contain many useful information, see what other extension authors do
* [x] Make sure to use headline elements and other formatting, see http://wiki.typo3.org/ReST_Syntax
* [x] Add a section about how to use preview post functionality

### CODE REVIEW

**Comment by fnagel** [comment]
Ok, I did a first review and added a bunch of inline comments. Additionally I added a todo list in the PR description.

I would advise you to add a "done" comment for each of my comments. This way its easier to track which issues have already been fixed.

**Comment by fnagel** [comment]
Rebased onto latest dev branch and fixed commit messages. 
Some general fixes and improvements. 

Still needs some more love (see PR description)

**Comment by fnagel** [comment]
Rebased onto latest dev branch and fixed commit messages.
Some general fixes and improvements.

Still needs some more love (see PR description)

**Comment by criwe** [comment]
Added a section about the E-Mail stuff (administratior manual), is not submit atm.

**Comment by fnagel** [comment]
@criwe Where is that "Email stuff" section? I see no new commits here...

**Comment by criwe** [comment]
@fnagel just added the commit

**Comment by fnagel** [comment]
@criwe Ahem, seems like you didn't :-)

**Comment by criwe** [comment]
... sync failed.... any ideas?!

Conflicts:
	Documentation/AdministratorManual/Index.rst
	Documentation/Configuration/Index.rst
	Documentation/UsersManual/Index.rst

**Comment by fnagel** [comment]
You will need to do a forced pull as I rebased the changes. Make sure to backup your changes as with force all your changes will be overwritten.

**Comment by criwe** [comment]
[x], hope i´ve remembered all change, but think so.

**Pull request merged**
