### PR TITLE
[FIX] Invoke Condition Check in compiled CommentAllowedViewHelper

### PR DESCRIPTION
**Pull request by pvanhemmen**
This Fix invokes a correct condition check for the compiled CommentAllowedViewHelper.

The \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractConditionViewHelper implements the newly introduced \TYPO3\CMS\Fluid\Core\ViewHelper\Facets\CompilableInterface and caches if/else conditions once executed. This leads to the unexpected behaviour of commenting being disallowed once the condition is cached.

This solution prevents the static compilation of the view helpers condition, instead making sure the condition is checked everytime the viewhelper is called, as it was done before in TYPO3 6.x, by returning the appropriate value in the compile method. This is necessary if one needs to bypass static rendering and invoke the condition check at runtime.

From the \TYPO3\CMS\Fluid\Core\ViewHelper\Facets\CompilableInterface PHPDoc of the compile method:

        Return Value
	 * ============
	 * Besides returning a single string, it can also return the constant
	 * \TYPO3\CMS\Fluid\Core\Compiler\TemplateCompiler::SHOULD_GENERATE_VIEWHELPER_INVOCATION
	 * which means that after the $initializationPhpCode, the ViewHelper invocation
	 * is built as normal. This is especially needed if you want to build new arguments
	 * at run-time, as it is done for the AbstractConditionViewHelper.

It seems to me that something's messed up here, since the AbstractConditionViewHelper mentioned in the comment is the one view helper right now where SHOULD_GENERATE_VIEWHELPER_INVOCATION is not returned.

### CODE REVIEW

**Comment by fnagel** [comment]
Related to #23

Thanks a lot, I already had a hard time with this issue. Works like a charm
and will be merged soon!

Was this behaviour change documented somewhere?

**Comment by pvanhemmen** [comment]
Unfortunately I didn't find any documentation about this change (the affected methods are all marked as internal), so I doubt the default cashing even behaves correct the way it does now. My Fix is somewhat based on assumptions and debugging, I basically traced the rendering callstack of the Viewhelper and tracked it down to being a difference in the \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractConditionViewHelper from 6.x > 7.x where it now implements \TYPO3\CMS\Fluid\Core\ViewHelper\Facets\CompilableInterface. The php doc comments of this class led me to the conclusion I came up with.

Besides that, I don't understand why
1. the system seems to cache an empty condition and NOT the case it encountered when rendered for the first time.
2. if/else conditions within view helpers should be cached by default anyway.

I would be delighted if anyone could shed some light on the internals of the cashing that's been introduced here.

**Comment by fnagel** [comment]
Merged in 2aa9174499543e1dde2deba3d2fd1511ab21ba72

**Comment by fnagel** [comment]
Mhh ok, thanks for the background infos. Seems should have been mentioned somewhere in the core upgrade guides. 

Again, thanks a lot for this fix!

**Pull request closed without merging**
