### PR TITLE
Flexformconfig for blogsystem.pid

### PR DESCRIPTION
**Pull request by madaxel**
Might be related to https://github.com/fnagel/t3extblog/issues/12

### CODE REVIEW

**Comment by fnagel** [comment]
Sorry for the late response. It seems I missed this one after adding the label.

I'm not sure if its a good idea to allow to change the blogsystem pid via flexform because the blogsystem.pid is needed in BE context too. I would assume we'll run into issues when sending emails in a non FE context (aka via the TCA hooks). Any experience with this concern when using the flexform? Can you please test this and give feedback?

**Comment by madaxel** [comment]
I'll Test this.
In my Context i have setup two pages with its own Blog (one for projects and one for smalltalk stuff). I assumed that this would work and just got trouble to set up a frontpage on which i'd like to teaser both blogcontents and show category menus.

**Comment by fnagel** [comment]
Having multiple blogs is with teasers for each blog on one page seems like a valid use case.

After reconsidering this it seems possible to use the flexform for the given plugins. I guess only the blogsystem plugin would lead to confusion and potentially errors. Please note its important to set the pid in TS where the blog post records are placed -- otherwise the BE hooks will fail.

I'm looking forward for your feedback!

**Comment by madaxel** [comment]
Hi Felix,
I checked the Email behaviour today. And found a potential Bug in the SettingsService, which results in wrong links (wrong blogsystem Pid) in the send Emails. 

After my patch the mail was send with the two correct links. (OptIn)

Since the TCA hooks should always know the PageId of the Object currently processed, the settingsservice can load the corresponding configuration and should this way work with the correct blogsystempid.

For this to work you have to use one sysfolder for each blogsystem you have, which I thing is desired at all.

I added flexform for Archive and RSS to configure blogsystem.pid

I haven't used the subscriber plugin in real world, but I thing it could work without knowing the blogsystem.pid so there is no need to setup flexform here.

Hope that I'm on the right track to setup multiple Blogs.

Current Pagelayout for two blogs
| root
-| blog
--| blogentries
-|projects
--| projectentires
-|subscribers (untested)

**Comment by fnagel** [comment]
> For this to work you have to use one sysfolder for each blogsystem you have, which I thing is desired at all.

Using multiple sysfolders is the correct way of doing this, yes. 

> Hope that I'm on the right track to setup multiple Blogs.
 I would recommend using one folder for all blog related records. Structure like this:

````
- root
  - some page
  - blog 1
    - subscription manager blog 1
    - sysfolder for blog 1
  - some page 
  - blog 2
    - subscription manager blog 2
    - sysfolder for blog 2
````

Am I right you just changed the position in the setPageUid method? Uhh, this method is really sensitive. Needs testing for multilanguage and TYPO3 6.2.

I'm thinking of making the blogsystem.pid flexform optional (perhaps via EM if possible) as using this without a lot of care will result in a lit of errors. One need to make sure the pid is configured for teh sysfolders accordingly.

Not sure if a flexform is really needed for RSS as a single page is needed anyway.

**Comment by madaxel** [comment]
Jep, only changed position. Since the getconfiguration needs to know the pid.

Checkbox in em seems a good solution to keep setup as simple as possible. I don't know if this is possible...

With RSS Young are right. I'll remove that one tomorrow.

**Comment by fnagel** [comment]
> Checkbox in em seems a good solution to keep setup as simple as possible. I don't know if this is possible...

Same here. We'll see if this possible. EM config for adding flexform for sure, but single flexform field only via TSconfig. Using `TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addUserTSConfig` should do the trick.

**Comment by fnagel** [comment]
Please note: this PR is not forgotten but on hold for now until release of version 2.0.0. I will test this asap. Thanks for your contribution!

**Comment by madaxel** [comment]
Hi Felix,
just take your time. I'm quite busy right now. I think there's still some work left to do. For me it is working on my multiblog site (using 7.6 btw), but i do not really make use of the subscriptionmanager and don't find time to get it setup and invite others to use the new blog.

So no pressure here ;-)
Markus

**Comment by fnagel** [comment]
Closed as outdated. Sorry for that.

**Pull request closed without merging**
