### PR TITLE
[BUGFIX] Add missing fields for workspace/version integration

### PR DESCRIPTION
**Pull request by tomhatzer**
The field t3ver_move_id is missing from the tx_t3blog_cat table.

### CODE REVIEW

**Comment by tomhatzer** [comment]
@fnagel I changed the title of the PR, I'll see how I can change the titles of the commits as I only did this using the website...

**Comment by tomhatzer** [comment]
@fnagel can you please have a look and tell me if it's ok now?

**Comment by fnagel** [comment]
@tomhatzer The commits message are fine now, but you should have rebased your local branch instead of merging to keep the history more clean.

I've just cherry picked your new commits. Thanks for your contribution!

Merged in bc52373391786464afddbdcba2dd8d648b513445 and c4b591a23ba7e0b9f39aace26ad820e8ed81e865

Closes #198

**Comment by tomhatzer** [comment]
Thank you very much and sorry for the mess!

**Pull request closed without merging**
