### PR TITLE
Add slash to regex for category_title

### PR DESCRIPTION
**Pull request by tomhatzer**
Fixes https://github.com/fnagel/t3extblog/issues/230#issuecomment-654723276

### CODE REVIEW

**Comment by fnagel** [comment]
Thanks for the contribution!

Mhh, this will allow using `/` within the category object `url_segment` field, correct? Not sure if that is something we want for this field. Actually, the TCA config should replace slashes: https://github.com/fnagel/t3extblog/blob/master/Configuration/TCA/tx_t3blog_cat.php#L183-L185

Can you give me a field value and URL example when this happens in your setup?

**Comment by tomhatzer** [comment]
Hi @fnagel :)
Sure thing, this happens on the blog category overview page and the url is "blog/fachbeitraege". I haven't set this on my own anywhere and don't know where this is coming from 🤷‍♂️
The error message is in this comment here including the path: https://github.com/fnagel/t3extblog/issues/230#issuecomment-654723276

**Comment by tomhatzer** [comment]
@fnagel I just saw that the migrations from the Typo3 8 to Typo3 9 created a category name blog/fachbeitraege for the url_segment column in the tx_t3blog_cat table. I'll change it to blog-fachbeitraege.

**Comment by tomhatzer** [comment]
I'll close this as it was a mistake on my side. Thanks for helping out 😁

**Comment by fnagel** [comment]
Thanks for the feedback!

Do you think this is an issue with the update wizard script? Do we need to adjust something?

It SHOULD remove those slashes, since its using the slug service generate method, see d877c1638e73a5b96470449eeed4249d896c2df1

Did you probably use the migration wizard before this was fixed (before d877c1638e73a5b96470449eeed4249d896c2df1 or 7bee80c15f364dd220f29680bfd83d04004a56f9)?

**Pull request closed without merging**
