### PR TITLE
change CSS icon  class for comment to icon-comment

### PR DESCRIPTION
**Pull request by madaxel**
CSS class for comment icon should be icon-comment instead of icon-comments
same for glyphicon

### CODE REVIEW

**Comment by fnagel** [comment]
I don't see any reason to change this to a single comment icon. In addition, if this would be changed, it would make sense to change the tag icon too.

**Comment by pvanhemmen** [comment]
In addition, if you need to overwrite single templates because you need different icons, you can do this by overwriting  views with your own templates by defining a different template path for t3extblog with fallbacks to the default template set. http://www.dennislizarzaburu.de/blogs/16/Mehrere+Pfade+f%C3%BCr+Templates,+Layouts+und+Partials+in+Typo3+6.2
The example is in german and for tx_news but the code works the same way for t3extblog. Hope that helps.

**Comment by madaxel** [comment]
The problem i have is just seeing no Icon at all if class is Icon-comments. Maybe i have an old version of the icon font. I'll Check that later and report back.

Thanks for the additional hint.

**Comment by fnagel** [comment]
Ok, not having an icon at all seems like an issue we should fix! Perhaps we need to adjust the glyhpicon class only.

Please test and give feedback!

**Comment by madaxel** [comment]
icon-comments class is change back. glyphicon-comment is enough to show an icon

**Comment by fnagel** [comment]
Sorry, not sure what's your point here. 

I guess `icon-comments` fontAwesome and changing back to `glyphicon-comment` for Bootstrap should be the way to go, ending up with: 

````icon icon-comments glyphicon glyphicon-comment````

**Comment by fnagel** [comment]
I will merge this PR soon.

**Comment by fnagel** [comment]
Thanks for your contribution!

**Pull request closed without merging**
